### ISSUE TITLE
No way to contact you - Saturn in live broadcast

### ISSUE THREAD

**Issue by GrahamCCRL** [egormoroz/saturn#2]
106TH AMATEUR SERIES (Division 8 )

Dumb 2.0 64-bit (relegated)
JackyChess 23.12 64-bit (relegated)
Colossus 2022a 64-bit (2022-05)
Fridolin 4.0 64-bit (2022-06) (relegated)
MadChess 3.2 64-bit
Nawito 22.07 64-bit
KnightX 3.9 64-bit
CT800 1.45 64-bit (relegated)
Boychesser 1.0 64-bit (new)
Lozza 2.5 64-bit
Saturn 1.0 64-bit (new)
Sirius 5.0 64-bit
Rengar 1.3.0 64-bit
Raven 1.30 64-bit (promoted)

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16064

**Comment by egormoroz** [comment]
Hi,
Thank you for notifying! It was extremely exciting to watch my engine play against others (and a little nerve-wracking, since it was at the bottom during the first few rounds). Also, I wonder how my engine ended up participating in this tournament (and on the CCRL board as well), since I never really submitted it anywhere. Not that I mind, of course, just a little curious.

**Comment by GrahamCCRL** [comment]
Hi,

Norman Schmidt found Saturn and suggested that it could be tested for CCRL.
:-)

Graham.

**Comment by GrahamCCRL** [comment]
Hi ,

Are you using a 'borrowed' NNUE or is Saturn using an original one?

Graham (CCRL)

**Comment by egormoroz** [comment]
The NNUE I'm using is trained completely from scratch on selfplay data, using my own pytorch trainer. I'm considering releasing the complete training logs and checkpoints a little later, once they aren't as messy, though if some kind of confirmation needed I can publish the wandb logs tomorrow.

**Comment by GrahamCCRL** [comment]
Well done! :-)
I've moved Saturn up a couple of divisions.

Graham.

**Comment by egormoroz** [comment]
Thank you, that's great!

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Thu, Mar 21, 2024 at 4:42 PM
Subject: 107th Amateur Division 6
To: Andres Manzanares ***@***.***>, David <
***@***.***>, Krasimir Topchiyski ***@***.***>


*107TH AMATEUR SERIES (Division 6)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
2600+8moves.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will be promoted, while the bottom engine will be
relegated. Any other changes of division will be at my discretion and may
not necessarily involve playoff matches.*

*Participants*

Atlas 4.35 64-bit
Orion 1.0 64-bit
Saturn 1.1 64-bit *(promoted)*
GOOB 1.8.9 64-bit
Princhess 0.16.0 64-bit
Wahoo 4.0 64-bit *(relegated)*
4ku 4.0 64-bit
Bagatur 4.1a 64-bit
Ceibo 1.0 64-bit
Vengeance 3.0.0 64-bit
Zangdar 2.27.08 64-bit
Cadie 1.5 64-bit *(promoted)*
Sirius 6.0 64-bit *(promoted)*
ice4 4.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16073

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Wed, May 15, 2024 at 10:53 AM
Subject: New Tournament
To: Peter Osterlund ***@***.***>, mar ***@***.***>,
Vincent Yu ***@***.***>, Archishmaan Peyyety ***@***.***>


*RENEGADE IN THE PADDY FIELD*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 36 rounds
All engines 1CPU


*Participants*

Rice 8.0.0 64-bit
Texel 1.11 64-bit
Cheng 4.48 64-bit
Midnight 9.0 64-bit
Motor 0.4.0 64-bit
Renegade 1.0.0 64-bit
chess.cpp 4.0 64-bit
Saturn 1.3 64-bit
Mr Bob 1.3.0 64-bit
Expositor 4WR02 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16071

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16071
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sat, Jun 1, 2024 at 10:33 AM
Subject: 109th Amateur Series Division 4
To: mar ***@***.***>, ***@***.***>, <
***@***.***>, Alcides Schulz ***@***.***>,
Yinuo H ***@***.***>, Vadim Chizhov ***@***.***>, <
***@***.***>


*109TH AMATEUR SERIES (Division 4)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will gain automatic promotion and the bottom engine will
gainface automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*

*Participants*

Cheng 4.48 64-bit
SmallBrain 7.0 64-bit
Halogen 11 64-bit *(relegated)*
Saturn 1.3 64-bit
StockDory Starfish 0.1 64-bit
Mr Bob 1.3.0 64-bit *(promoted)*
Expositor 4WR02 64-bit
Tucano 11.00 64-bit
Avalanche 2.1.0 64-bit *(relegated)*
Counter 5.5 64-bit
Molybdenum 3.1 64-bit *(promoted)*
Devre 5.0 64-bit
Reckless 0.6.0 64-bit *(promoted)*
Stash 35.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16069

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16069
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Mon, Jun 24, 2024 at 10:44 PM
Subject: New Tournament
To: ***@***.***>, mar ***@***.***>, Vincent Yu <
***@***.***>, ***@***.***>, Vadim Chizhov <
***@***.***>


*MINERALS AND GASES*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU


*Participants*

SmallBrain 7.0 64-bit
BlackCore 6.0 64-bit
chess.cpp 4.0 64-bit
Halogen 11 64-bit
Saturn 1.3 64-bit
Cheng 4.48 64-bit
Serendipity 0.2 64-bit
Mr Bob 1.3.0 64-bit
Expositor 4WR02 64-bit
Counter 5.5 64-bit
Molybdenum 3.1 64-bit
Winter 3.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16068

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16068
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Tue, Jul 30, 2024 at 5:40 PM
Subject: New Tournament
To: mar ***@***.***>, Vincent Yu ***@***.***>, Krasimir
Topchiyski ***@***.***>, Christian Günther ***@***.***>,
Martin Danielsson ***@***.***>


*ENTANGLED*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU


*Participants*

Spaghet MariNNara 1.0 64-bit
Marvin 6.3.0 64-bit
Midnight 9.0 64-bit
Cheng 4.48 64-bit
Serendipity 0.3.1 64-bit
chess.cpp 4.0 64-bit
Saturn 1.3 64-bit
Nemorino 6.05 64-bit
Molybdenum 3.1 64-bit
Expositor 4WR02 64-bit
Bagatur 5.1 64-bit
Mr Bob 1.3.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16073
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Thu, Aug 22, 2024 at 9:00 AM
Subject: 111th Amateur Series Division 4
To: mar ***@***.***>, Martin Danielsson ***@***.***>,
Krasimir Topchiyski ***@***.***>, Yinuo H ***@***.***>,
Alcides Schulz ***@***.***>, ***@***.***>


*111TH AMATEUR SERIES (Division 4)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

*The top engine will gain automatic promotion and the bottom engine will
face automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*

*Participants*

Serendipity 0.4 64-bit
Devre 6.0 64-bit
Marvin 6.3.0 64-bit
Cheng 4.48 64-bit *(relegated)*
Molybdenum 4.0 64-bit
SmallBrain 7.0 64-bit
chess.cpp 4.0 64-bit
Blackcore 6.0 64-bit *(relegated)*
Saturn 1.3 64-bit
StockDory Starfish 0.1 64-bit
Bagatur 5.1b 64-bit *(promoted)*
Avalanche 2.1.0 64-bit
Tucano 11.00 64-bit
Stash 36.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16068

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16068
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Fri, Sep 27, 2024 at 11:21 PM
Subject: 112th Amateur Series Division 4
To: Martin Danielsson ***@***.***>, mar ***@***.***>, <
***@***.***>


*112TH AMATEUR SERIES (Division 4)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

*The top engine will gain automatic promotion and the bottom engine will
face automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*

*Participants*

Texel 1.11 64-bit *(relegated)*
Bagatur 5.1c 64-bit
Integral v4 64-bit *(promoted)*
Marvin 6.3.0 64-bit
Midnight 9.0 64-bit *(relegated)*
Quanticade Aurora 0.8 64-bit *(new)*
Cheng 4.48 64-bit
Reckless 0.7.0 64-bit
SmallBrain 7.0 64-bit
chess.cpp 4.0 64-bit
Saturn 1.3 64-bit
Molybdenum 4.0 64-bit
Expositor 4WR02 64-bit *(promoted)*
Stash 36.0 64-bit *(promoted)*


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16069

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16069
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*113TH AMATEUR SERIES (Division 4)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

*The top engine will gain automatic promotion and the bottom engine will
face automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*

*Participants*

chess.cpp 4.10 64-bit
Serendipity 0.4.1 64-bit *(relegated)*
Wasp 7.00 64-bit *(relegated)*
Reckless 0.7.0 64-bit
Marvin 6.3.0 64-bit
Midnight 9.0 64-bit
Cheng 4.48 64-bit
Bagatur 5.1c 64-bit
SmallBrain 7.0 64-bit *(02-2023)*
Sapling 1.2.2 64-bit *(promoted)*
Saturn 1.3 64-bit
Molybdenum 4.1 64-bit
StockDory Starfish 0.1 64-bit *(promoted)*
Stash 36.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16067

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16067
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Mon, Dec 16, 2024 at 12:10 PM
Subject: 114th Amateur Series Division 5
To: Alcides Schulz ***@***.***>, Krasimir Topchiyski <
***@***.***>, ***@***.***>, Yinuo H <
***@***.***>, ***@***.***>, Tsoj Tsoj <
***@***.***>, ***@***.***>, Vadim Chizhov <
***@***.***>


114TH AMATEUR SERIES (Division 5)

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds

Tucano 12.00 64-bit
Bagatur 5.1c 64-bit (relegated)
Sapling 1.2.2 64-bit (relegated)
Saturn 1.3 64-bit (relegated)
Calvin 5.0.2 64-bit
Sirius 8.0 64-bit
StockDory Starfish 0.1 64-bit (relegated)
Ynode 0144 64-bit
Avalanche 2.1.0 64-bit
Expositor 4WR02 64-bit
Stash 36.0 64-bit (relegated)
Counter 5.5 64-bit
Nalwald 19.0 64-bit
LG Evolution NN 3.17 64-bit (promoted)

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16065

**Comment by GrahamCCRL** [comment]
122ND AMATEUR SERIES (Division 6) AMD Ryzen 5950x ChessGUI 256mb hash each
where possible
6 piece tablebases Ponder off GBSelect2025B.cgb book 12 minutes with 8
second increments. 6 cycles 78 rounds Iris 2.0 64-bit (relegated) Weiawaga
6.0 64-bit Lambergar 1.3 64-bit (relegated) Stash 37.0 64-bit Saturn 1.3
64-bit (04-2024) (relegated) Illumina 3.0 64-bit Molybdenum 4.1 64-bit
(06-2024) Pedantic 2.1.0 64-bit (09-2024) Perseus 1.1 64-bit Rebel Extreme
1.1 64-bit Avalanche 2.1.0 64-bit (01-2024) (relegated) Clockwork
dev-20251124 64-bit (promoted) Lynx 1.11.0 64-bit (promoted) Schoenemann
0.4.0 64-bit Web based link for live viewing (courtesy of Jay - Berserk
author). https://ccrl.live/16070

**Comment by GrahamCCRL** [comment]
Can I please add your name and nationality?

Just let me know those details.

Regards,
Graham.
